const radiografiasPacientes =
[{
    // PRIMER OBJETO
    INDEX: 0,
    NOMBRES: "GISELLE CAMILA",
    APELLIDOS: "GONZALEZ CIFUENTES",
    IMAGENES: "https://radiologiadentallaspalmas.com/wp-content/uploads/2019/07/post.-pan.jpeg",
    TipoDocumento: "CEDULA",
    ID: "1018478587",
    SEXO: "FEMENINO",
    EDAD: "34",
    ALTURA: "1.60",
    PESO: "60",
    SERVICIO: "ORTODONCIA",
    PROCEDIMIENTO: "RETIRO",
    ESTUDIO: "PANORAMICA",
    ZONA: "COMPLETA",
    EQUIPO: "TOMOGRAFO ODONTOLÓGICO",
    MARCA: "MYRAY",
    MODELO: "HYPERION X9",
    SERIAL: "D898ED34",
    CONSULTORIO: "RAYOS X",
    FECHA: "1/05/2023",
    DOSIS: "264.6",
    totalDosis: "264.6",
    KV: "90",
    MA: "10",
    TIEMPO: "16",
    tomasBuenas: "1",
    tomasMalas: "0",
    TOTAL: "1",
    causaRepeticion: "Ninguna",
    NombreProfesional: "JEIMY CIFUENTES",
    documentoProfesional: "123456786",
    cargoProfesional: "AUXILIAR EN SALUD ORAL",
},
{
    // SEGUNDO OBJETO
    INDEX: 1,
    NOMBRES: "YESICA ANDREA",
    APELLIDOS: "SOLER LOPEZ",
    IMAGENES:"https://globalimagen.com.ec/wp-content/uploads/2023/02/45-Radiografia-dental-periapical.webp",
    TipoDocumento: "CEDULA",
    ID: "1012345678",
    SEXO: "FEMENINO",
    EDAD: "18",
    ALTURA: "1.54",
    PESO: "45",
    SERVICIO: "GENERAL",
    PROCEDIMIENTO: "LIMPIEZA",
    ESTUDIO: "RX PERIAPICAL",
    ZONA: "23",
    EQUIPO: "PERIAPICAL",
    MARCA: "MYRAY",
    MODELO: "RXDC EXTEND",
    SERIAL: "7A06J45",
    CONSULTORIO: "CONSULTORIO",
    FECHA: "2/05/2023",
    DOSIS: "4",
    totalDosis: "12",
    KV: "70",
    MA: "8",
    TIEMPO: "0.2",
    tomasBuenas: "1",
    tomasMalas: "2",
    TOTAL: "3",
    causaRepeticion: "Falla en digitalización imagen",
    NombreProfesional: "JEIMY CIFUENTES",
    documentoProfesional: "123456786",
    cargoProfesional: "AUXILIAR EN SALUD ORAL",
},
{
    // TERCER OBJETO
    INDEX: 2, 
    NOMBRES: "WILSON ALBERTO",
    APELLIDOS: "ESCOBAR ESCOBAR",
    IMAGENES: "https://imagenrx.net/wp-content/uploads/2019/06/serv_tunm.jpg", 
    TipoDocumento: "CEDULA EXTRANJERA",
    ID: "5432357",
    SEXO: "MASCULINO",
    EDAD: "60",
    ALTURA: "1.85",
    PESO: "70",
    SERVICIO: "CIRUGIA",
    PROCEDIMIENTO: "INSTALACION IMPLANTE",
    ESTUDIO: "TOMOGRAFIA",
    ZONA: "ZONA SUPERIOR",
    EQUIPO: "TOMOGRAFO ODONTOLÓGICO",
    MARCA: "MYRAY",
    MODELO: "HYPERION X9",
    SERIAL: "D898ED34",
    CONSULTORIO: "RAYOS X",
    FECHA: "3/05/2023",
    DOSIS: "200",
    totalDosis: "400",
    KV: "90",
    MA: "10",
    TIEMPO: "13",
    tomasBuenas: "1",
    tomasMalas: "1",
    TOTAL: "2",
    causaRepeticion: "Movimiento del paciente",
    NombreProfesional: "JEIMY CIFUENTES",
    documentoProfesional: "123456786",
    cargoProfesional: "AUXILIAR EN SALUD ORAL",
},
{
    // CUARTO OBJETO
    INDEX: 3,
    NOMBRES: "JUAN CAMILO",
    APELLIDOS: "GUILLEN BARBOSA",
    IMAGENES:"https://www.actaodontologica.com/ediciones/2012/4/art-22/3.jpg",
    TipoDocumento: "CEDULA",
    ID: "123056498",
    SEXO: "MASCULINO",
    EDAD: "20",
    ALTURA: "1.77",
    PESO: "84",
    SERVICIO: "ENDODONCIA",
    PROCEDIMIENTO: "RETIRO CALCULO",
    ESTUDIO: "RX PERIAPICAL",
    ZONA: "34",
    EQUIPO: "PERIAPICAL",
    MARCA: "MYRAY",
    MODELO: "HYPERION X9",
    SERIAL: "A06J45",
    CONSULTORIO: "CONSULTORIO",
    FECHA: "4/05/2023",
    DOSIS: "0,23",
    totalDosis:"0,23",
    KV: "65",
    MA: "8",
    TIEMPO: "0.230",
    tomasBuenas: "1",
    tomasMalas: "0",
    TOTAL: "1",
    causaRepeticion: "Ninguna",
    NombreProfesional: "JEIMY CIFUENTES",
    documentoProfesional: "123456786",
    cargoProfesional: "AUXILIAR EN SALUD ORAL",
},
{
    // QUINTO OBJETO
    INDEX: 4,
    NOMBRES: "YESICA PAOLA",
    APELLIDOS: "JARAMILLO GUTIERREZ",
    IMAGENES: "https://radiologiadentallaspalmas.com/wp-content/uploads/2019/06/Escaner-dental.jpg",
    TipoDocumento: "CEDULA",
    ID: "1111145532",
    SEXO: "FEMENINO",
    EDAD: "23",
    ALTURA: "1.54",
    PESO: "60",
    SERVICIO: "REHABILITACIÓN",
    PROCEDIMIENTO: "REHABILITACIÓN IMPLANTE",
    ESTUDIO: "TOMOGRAFÍA",
    ZONA: "INFERIOR",
    EQUIPO: "TOMOGRAFO ODONTOLÓGICO",
    MARCA: "MYRAY",
    MODELO: "HYPERION X9",
    SERIAL: "D898ED34",
    CONSULTORIO: "RAYOS X",
    FECHA: "5/05/2023",
    DOSIS: "342",
    totalDosis: "342",
    KV: "90",
    MA: "10",
    TIEMPO: "16",
    tomasBuenas: "1",
    tomasMalas: "0",
    TOTAL: "1",
    causaRepeticion: "Ninguna",
    NombreProfesional: "JEIMY CIFUENTES",
    documentoProfesional: "123456786",
    cargoProfesional: "AUXILIAR EN SALUD ORAL",
},
{
// SEXTO OBJETO
    // QUINTO OBJETO
    INDEX: 5,
    NOMBRES: "ESTEBAN",
    APELLIDOS: "SALAMANCA PULIDO",
    IMAGENES: "https://dentometric.com/wp-content/uploads/2019/12/1.png",
    TipoDocumento: "CEDULA",
    ID: "1018345654",
    SEXO: "MASCULINO",
    EDAD: "55",
    ALTURA: "1.75",
    PESO: "80",
    SERVICIO: "ORTODONCIA",
    PROCEDIMIENTO: "RETIRO",
    ESTUDIO: "PANORAMICA",
    ZONA: "COMPLETA",
    EQUIPO: "TOMOGRAFO ODONTOLÓGICO",
    MARCA: "MYRAY",
    MODELO: "HYPERION X9",
    SERIAL: "D898ED34",
    CONSULTORIO: "RAYOS X",
    FECHA: "6/05/2023",
    DOSIS: "462",
    totalDosis: "462",
    KV: "90",
    MA: "10",
    TIEMPO: "16",
    tomasBuenas: "1",
    tomasMalas: "0",
    TOTAL: "1",
    causaRepeticion: "Ninguna",
    NombreProfesional: "JEIMY CIFUENTES",
    documentoProfesional: "123456786",
    cargoProfesional: "AUXILIAR EN SALUD ORAL",
}
];

export default radiografiasPacientes;